version: '3.8'

services:
  # MySQL 컨테이너 설정
  mysql:
    image: mysql:8.0.38
    container_name: ticket-msa-mysql
    ports:
      - "3307:3306"  # (내 컴퓨터 포트) : (컨테이너 포트)
    environment:
      MYSQL_ROOT_PASSWORD: root       # 비밀번호 1234로 고정
      MYSQL_DATABASE: ticket_concert  # 시작할 때 이 DB를 자동 생성 (핵심!)
      TZ: Asia/Seoul                  # 시간대를 한국으로 설정
    volumes:
      - ./db/data:/var/lib/mysql      # 데이터를 내 컴퓨터 폴더(db/data)에 저장 (삭제 방지)
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always